name: Pipeline

on:
  workflow_dispatch:

jobs:
  ci:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        working-directory: python-app-code
        run: |
          python -m pip install --upgrade pip
          pip install pytest flake8 black

      - name: Run flake8
        working-directory: python-app-code
        run: python -m flake8 .

      - name: Run black
        working-directory: python-app-code
        run: python -m black --check .

      - name: Run tests
        working-directory: python-app-code
        run: python -m pytest -v